### ISSUE TITLE
Lat and Lon Wrong in Some Parks

### ISSUE THREAD

**Issue by endingeons** [davidye007/NPSpecies_US_NationalParks#1]
Source: us-national-parks-with-regions.csv

The longitudes are incorrect for the following parks.

park_id

park_indiana-dunes
park_gateway-arch
park_white-sands

It looks like the data was imported where a negative sign is missing from the longitude.

For example, park_gateway-arch is lat: 38.63 lon: 90.2 which puts this park in China. Should be corrected to -90.2.

**Comment by endingeons** [comment]
Additionally, park_new-river-gorge

**Comment by davidye007** [comment]
@endingeons corrected the longitudes of white sands, new river gorge, indiana dunes, and gateway arch national parks.
